agent:
  max_steps: 10
api:
  MAKCORPS_API_KEY: None
  OLLAMA_API_KEY: None
  wiki_user_agent: None
input:
  user_input: What's the weather in Chengdu?
model:
  agent_model_name: qwen3:8b
  agent_model_temperature: 0.7
  judgement_model_name: qwen3:8b
  judgement_model_temperature: 0
  planner_model_name: qwen3:8b
  planner_model_temperature: 0
output:
  log_file: agent_execution_log.txt
tools:
  tool_registry:
    calc: calculator_tool
    search: search_tool
    weather: get_weather_tool
  use_hotel_price_lookup: false
  use_internet_search: false
  use_judgement_model: true
  use_planner: false
  use_wikipedia_search: false
